### PR TITLE
add type boolean logic for requiredIf and requiredNotIf

### PR DESCRIPTION
**Pull request by dotjoshrc**
Love the library!

Ran into an issue where using the `requiredIf` and `requiredIfNot` would not properly validate a boolean on the field you are requiring based on. Example below:

``` js
yield this.validateBody({
    isGuest: 'required|boolean',
    guest: 'requiredIf:isGuest,true'
});
```

If you were posting something like the following, guest would not be required. My fix will even work for 0 and 1 because `JSON.parse()` will convert 0 or 1 to a boolean. 

``` js
{
    "isGuest": true
}
```

### CODE REVIEW

**Comment by srinivasiyer** [comment]
Hey Josh,

There is an alternative way to validate fields. Check the following link.

https://koa-validation.readme.io/docs/required-rules

You could make a tweak to the above code and write it following way.

```
yield this.validateBody({
    isGuest: 'required|boolean',
    guest: { requiredIf: [ 'isGuest', true ] }
});
```

**Comment by dotjoshrc** [comment]
Ah cool I was looking for something of the sort but overlooked that. Would still be nice for the shorthand though

**Comment by dotjoshrc** [comment]
@srinivasiyer using your example i'm noticing a bug with defining the following:

``` js
yield this.validateBody({
    isGuest: 'required|boolean',
    guest: { requiredIf: ['isGuest', true] },
    user: { requiredIf: ['isGuest', false] }
});
```

This fails to properly validate when passing `isGuest: false` in POST. It passes validation for `user` when it should not. I verified that my pull request fixes this as well.

**Comment by dotjoshrc** [comment]
Any update on this? I'm having issues finding how your solve is chain-able with other validators.

**Comment by srinivasiyer** [comment]
Hi Josh,

Please give me time till the weekend to analyse the problem. I shall have it sorted by then. I apologize for the delay. It has been a very busy time!!

**Comment by dotjoshrc** [comment]
Thanks for the reply! I totally understand

**Comment by srinivasiyer** [comment]
Hi Josh,

Sorry for all the delays. I just made some changes to fix the bug but the approach is different from the one you used. There was an error in my code which was creating unable to identify the false condition in the requiredIf validator correctly. You will not not face an issue with it. 

However note that you would still need to use the

``` js
yield this.validateBody({
    isGuest: 'required|boolean',
    guest: { requiredIf: [ 'isGuest', false ] }
});
```

rather than

``` js
yield this.validateBody({
    isGuest: 'required|boolean',
    guest: 'requiredIf:isGuest,true'
});
```

Philosophically, I am a bit against recognizing a boolean within a string. I hope the patch helps. I am closing the pull request and hoping that this patch helps you solve your problems. Thanks again for spotting a rather hard to spot error. Appreciate the help.

**Comment by dotjoshrc** [comment]
@srinivasiyer Hey man, no worries. Thanks for the update! Will try it out!

**Pull request closed without merging**
